name: PluginCore.AspNetCore NuGet Push

on: 
  push:
    tags:
      - 'PluginCore.AspNetCore-v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    # 注意: 一定要有此步, 打包前端文件进入 dll, 需要在 dotnet build 前手动 npm install, csproj 中 NpmInstall 的仅对 vs 有效
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12

    - name: Build and Pack
      run: |
        cd ./src/PluginCore.AspNetCore
        # 注意: 一定要有此步
        npm install
        dotnet build --configuration Release
        dotnet pack --configuration Release
        dotnet pack --configuration Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
        ls
        ls ./bin/Release/
      shell: bash
        
    - name: Add private GitHub registry to NuGet
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/yiyungent/index.json --name github --username yiyungent --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
      shell: bash
        
    - name: Push generated package to GitHub registry and NuGet
      run: |
        # TODO: 未知原因, 与其它完全一致, 但这个就需要在这指定 --api-key ${{ secrets.GITHUB_TOKEN }}
        # 否则: warn : No API Key was provided and no API Key could be found for 'https://nuget.pkg.github.com/yiyungent'. To save an API Key for a source use the 'setApiKey' command.
        dotnet nuget push ./src/PluginCore.AspNetCore/bin/Release/*.nupkg --source github --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}
        dotnet nuget push ./src/PluginCore.AspNetCore/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NugetKey }}
      shell: bash
